version: "2"

services:
  frontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-smart-bike-light.rule=Host(`app.smart-bike-light.wiklosoft.com`)"
      - "traefik.http.services.app-smart-bike-light.loadbalancer.server.port=80"
      - "traefik.http.routers.app-smart-bike-light.entrypoints=websecure"
      - "traefik.http.routers.app-smart-bike-light.tls.certresolver=myresolver"

networks:
  default:
    external:
      name: pwiklowski_default
